package lexer;

/**
 * This file is automatically generated<br>
 * - it contains the enumeration of all of the tokens
 */
public enum Tokens {

    BogusToken, Program, Int, Float, BOOLean, If,
    Then, Else, Do, While, Function, Return,
    Identifier, INTeger, FLOAT, LeftBrace, RightBrace, LeftParen,
    RightParen, Comma, singleQuote, Assign, Equal, NotEqual,
    Less, LessEqual, Greater, GreaterEqual, Plus, Minus, Or,
    And, Multiply, Divide, Comment, ScientificN, SCIENTIFICN, Char, CHAR, Negation
}
